language: "en"

pipeline: "spacy_sklearn"

# data - this is the combined .md files

data: |
  ## intent:cancel_mission
  - stop the mission
  - cancel the mission
  - cancel your mission
  - cease and desist

  ## intent:current_mission
  - what are you doing?
  - what is your mission
  - what is your current mission

  ## intent:describe
  - tell me about [Prague](location)
  - I want to learn more about [Paris](location)
  - What is [New York City](location) like?
  - who is [Moneypenny](person)
  - do you know [Q](person)

  ## intent:frustrated
  - you are stupid
  - I can't stand you
  - shut up

  ## intent:goodbye
  - bye
  - goodbye
  - c ya
  - see you later
  - see ya
  - bye bye
  - cheers

  ## intent:hello
  - hello
  - hi
  - hey there
  - what's up?
  - hi there
  - howdy
  - greetings
  - good morning
  - good afternoon
  - good evening
  - hi, how are you?

  ## intent:say_your_name
  - what is your name
  - who are you
  - what should I call you
  - give me your name

  ## intent:start_mission
  - start a new mission
  - begin a mission
  - I have a new mission for you
  - Go to [Dallas](mission_destination) and [fly a helicopter](mission_objective)
  - I want you to [Eliminate Target X](mission_objective) in [Honduras](mission_destination)

  ## intent:store_name
  - my name is [Jason](user_name)
  - call me [Fred](user_name)
  - you can call me [Ralph](user_name)
  - I'm [Jane](user_name)
