policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 3
    augmentation: 20
    batch_size: 10
    validation: 0.2
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
