rest:
  # you don't need to provide anything here - this channel doesn't
  # require any credentialsrest:
  #   # you don't need to provide anything here - this channel doesn't
  #   require any credentials
